
name: 'AUTO Documentation'
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  BTD:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - { format: html,     branch: gh-pages }
        - { format: markdown, branch: documentation-markdown }
    name: 'ğŸ““ Docs | ${{ matrix.format }}'

    steps:

    - name: 'ğŸ§° Checkout'
      uses: actions/checkout@v2

    - name: 'âš™ï¸ Install TerosHDL and VUnit '
      run: |
        sudo pip3 install vunit_hdl
        git clone https://github.com/TerosTechnology/colibri.git
        cd colibri
        sudo npm install -g .
        sudo npm install -g teroshdl

    - name: 'ğŸ““ Generate documentation ${{ matrix.format }}'
      run: |
         python3 generate_doc.py html

    - name: 'ğŸ“¤ Upload artifact: ${{ matrix.format }}'
      uses: actions/upload-artifact@master
      with:
        name: documentation-${{ matrix.format }}
        path: teroshdl_doc

    - name: 'ğŸš€ Deploy'
      if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: ${{ matrix.branch }}
        folder: teroshdl_doc

